before_script:
  - pacman -Sy
  - pacman -S --noconfirm docker jdk21-openjdk

variables:
  JAVA_HOME: /usr/lib/jvm/java-21-openjdk

stages:
  - build
  - release

build-gradle-project:
  stage: build
  script:
    - ./gradlew application:build -Dorg.gradle.jvmargs=-Xmx1024m --stacktrace -Dquarkus.container-image.build=true
  variables:
    QUARKUS_CONTAINER_IMAGE_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

push-to-registry:
  stage: release
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
